/**
 * C2 COMPATIBILITY TEST — old `bcrypt` (native) hashes must verify under
 * `bcryptjs`.
 *
 * The server previously hashed passwords/verification codes with native
 * `bcrypt` 5.1.1. The dependency was swapped to pure-JS `bcryptjs` (drops
 * @mapbox/node-pre-gyp → tar, the critical advisory chain). bcryptjs
 * implements the same `$2a$/$2b$` bcrypt format, so every existing DB row
 * must continue to verify — proven here against REAL hashes generated by
 * the old native library BEFORE it was removed (embedded as literals, so
 * this test does not depend on the old package being installed).
 *
 * Cost factors covered: 10 (legacy verification codes) and 12 (passwords,
 * auth.service.ts), plus the `$2a$` prefix variant seen in older rows.
 *
 * Run with: npx vitest run src/__tests__/bcryptjs-compat.test.ts
 */
import { describe, it, expect } from 'vitest';
import bcrypt from 'bcryptjs';

// Generated with the OLD native bcrypt 5.1.1 (node -e "bcrypt.hash(...)"):
const PASSWORD = 'S3cret-Password!';
const OLD_HASH_COST_10 = '$2b$10$o8wKLyPb5NP1fO099QfYE.WDaU1K6S8asQ11FZjkKtXalchu7d0lS';
const OLD_HASH_COST_12 = '$2b$12$FLzePbZQZPRM2L7tM61j8.8nHcaoLxUxbRXnWMozrbVJAs/OmUMZC';
// Same hash with the legacy $2a$ prefix variant:
const OLD_HASH_2A = '$2a$12$FLzePbZQZPRM2L7tM61j8.8nHcaoLxUxbRXnWMozrbVJAs/OmUMZC';

describe('C2 — native bcrypt → bcryptjs hash compatibility', () => {
  it('verifies an existing cost-10 hash from the old library', async () => {
    await expect(bcrypt.compare(PASSWORD, OLD_HASH_COST_10)).resolves.toBe(true);
  });

  it('verifies an existing cost-12 hash from the old library (auth.service cost)', async () => {
    await expect(bcrypt.compare(PASSWORD, OLD_HASH_COST_12)).resolves.toBe(true);
  });

  it('verifies the legacy $2a$ prefix variant', async () => {
    await expect(bcrypt.compare(PASSWORD, OLD_HASH_2A)).resolves.toBe(true);
  });

  it('still REJECTS a wrong password against old hashes', async () => {
    await expect(bcrypt.compare('wrong-password', OLD_HASH_COST_12)).resolves.toBe(false);
  });

  it('new bcryptjs hashes use the same $2b$ format the old rows use', async () => {
    const fresh = await bcrypt.hash(PASSWORD, 12);
    expect(fresh.startsWith('$2b$12$') || fresh.startsWith('$2a$12$')).toBe(true);
    // …and a fresh hash round-trips through compare like the old ones
    await expect(bcrypt.compare(PASSWORD, fresh)).resolves.toBe(true);
  });
});
