import PublicPage from '../components/PublicPage';
import { usePageMeta } from '../lib/seo';

function LegalSection({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-bold text-white pt-4">{heading}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-sky-text-secondary">{children}</div>
    </section>
  );
}

export function TermsOfServicePage() {
  usePageMeta({
    title: 'Terms of Service',
    description:
      'The rules for using Aviator: who may play (18+), how accounts, bets, deposits and withdrawals work, and the terms that govern real-money play.',
    path: '/terms',
  });

  return (
    <PublicPage title="Terms of Service">
      <p className="text-xs text-sky-text-secondary/70">Last updated: September 2026</p>
      <LegalSection heading="1. Who may play">
        <p>
          Aviator is a real-money game of chance operated by Aviator Gaming,
          Addis Ababa, Ethiopia. You must be at least 18 years old and legally
          permitted to gamble in your jurisdiction to create an account or
          place a bet. One account per person; we may suspend accounts that
          break these rules.
        </p>
      </LegalSection>
      <LegalSection heading="2. Bets, outcomes and fairness">
        <p>
          Outcomes are generated by a commit/reveal system described on our{' '}
          <a href="/provably-fair" className="underline hover:text-white">provably fair page</a>{' '}
          and are fixed before betting opens. Bets cannot be cancelled once a
          round's betting window closes. The house edge is 3% and the game is
          designed so that, over time, the operator retains a statistical
          advantage — play for entertainment.
        </p>
      </LegalSection>
      <LegalSection heading="3. Deposits and withdrawals">
        <p>
          Deposits are credited after confirmation through the approved payment
          flow. Withdrawals are reviewed before payout and require identity
          verification where applicable. We may decline transactions that
          breach these terms, applicable law, or our fraud controls.
        </p>
      </LegalSection>
      <LegalSection heading="4. Responsible gaming">
        <p>
          You can request deposit limits or self-exclusion at any time via{' '}
          <a href="mailto:support@ethioaviator.com" className="underline hover:text-white">
            support@ethioaviator.com
          </a>
          . See our{' '}
          <a href="/responsible-gaming" className="underline hover:text-white">responsible gaming page</a>{' '}
          for tools and independent help resources.
        </p>
      </LegalSection>
      <LegalSection heading="5. Changes to these terms">
        <p>
          We may update these terms; material changes will be announced in the
          app. Continuing to play after a change means you accept the updated
          terms.
        </p>
      </LegalSection>
    </PublicPage>
  );
}

export function PrivacyPolicyPage() {
  usePageMeta({
    title: 'Privacy Policy',
    description:
      'What data Aviator collects, why, how long it is kept, and your rights: plain-language privacy policy covering account data, transactions, and financial records.',
    path: '/privacy',
  });

  return (
    <PublicPage title="Privacy Policy">
      <p className="text-xs text-sky-text-secondary/70">Last updated: September 2026</p>
      <LegalSection heading="1. What we collect">
        <p>
          Account data (name, email or phone), transaction records (deposits,
          withdrawals, bets, game rounds), and technical logs needed to run
          the service securely. Authentication is handled by our identity
          provider; we never store your password.
        </p>
      </LegalSection>
      <LegalSection heading="2. Why we collect it">
        <p>
          To operate your account, process payments, meet legal record-keeping
          obligations for real-money gaming, prevent fraud, and provide
          support. Financial records are retained as required by law.
        </p>
      </LegalSection>
      <LegalSection heading="3. What we never do">
        <p>
          We do not sell your personal data. We do not share it with third
          parties except payment processors, our identity provider, and where
          the law requires.
        </p>
      </LegalSection>
      <LegalSection heading="4. Your rights">
        <p>
          You can access or correct your data in your dashboard profile, or
          request export or deletion of personal data via{' '}
          <a href="mailto:support@ethioaviator.com" className="underline hover:text-white">
            support@ethioaviator.com
          </a>
          . Records we must keep for legal compliance are retained for the
          statutory period and then deleted.
        </p>
      </LegalSection>
      <LegalSection heading="5. Cookies and local storage">
        <p>
          We use local storage only to keep you signed in and remember your
          sound preference. No advertising or cross-site tracking cookies are
          used.
        </p>
      </LegalSection>
    </PublicPage>
  );
}
